### ISSUE TITLE
dipu需要支持获取tensor的storage地址及其偏移量，以及设备信息

### ISSUE THREAD

**Issue by squidlyy** [DeepLink-org/deeplink.framework#334]
在对tensor的部分数据进行处理时，目前的API仅支持获取data_ptr()，即tensor需要处理的数据的位置（已经过数据偏移）。
https://github.com/DeepLink-org/DIPU/blob/c3e0fec2581782f7dd6a959e6e1539e36c66c734/dipu/torch_dipu/csrc_dipu/diopirt/diopirt_impl.cpp#L24-L32
在实际开发中，在处理这部分数据时我们需要获取tensor的storage地址及偏移量，目前的dipu中并没有提供能够获取这些信息的API。

另外，在获取设备信息时，目前的dipu只能判断是device还是host；如果在多卡环境下，无法获取tensor的设备index信息。
https://github.com/DeepLink-org/DIPU/blob/c3e0fec2581782f7dd6a959e6e1539e36c66c734/dipu/torch_dipu/csrc_dipu/diopirt/diopirt_impl.cpp#L52-L56

这些信息都在at::Tensor中存在相关字段，dipu可以考虑增加获取这些字段的API。
![image](https://github.com/DeepLink-org/DIPU/assets/30268042/6a6f4f91-1f41-40f5-b103-3c8adce69df6)

**Comment by Gong-air** [comment]
您好，十分感谢您的建议。
这个issue我们会排期处理，如有后续，会及时进行更新。

**Comment by yangbofun** [comment]
diopirt.h需要添加获取storage地址和offset偏移的接口。以及获取设备index的接口。
