### ISSUE TITLE
首页缺少Readme

### ISSUE THREAD

**Issue by yewentao256** [DeepLink-org/deeplink.framework#416]
只有点击了dipu或者dicp才会有对应项目的Readme

此外，建议类似mmcv，添加双语介绍（中文、英文 可选）

**Comment by MiaoYYu** [comment]
[Readme](https://github.com/DeepLink-org/deeplink.framework/pull/450) 已补充

**Comment by yewentao256** [comment]
已approve，可以rerun一下CI，通过后合入
